import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "@/trpc/react";
import { NextAuthProvider } from "@/server/provider/nextAuthProvider";

import GoogleAnalytics from "@/components/GoogleAnalytics";
import CookieBanner from "@/components/cookieBanner";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <GoogleAnalytics GA_MEASUREMENT_ID="G-G1G7M329V0" />
      <body>
        <NextAuthProvider>
          <TRPCReactProvider>{children}</TRPCReactProvider>
          <CookieBanner />
        </NextAuthProvider>
      </body>
    </html>
  );
}
